version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  api:
    image: api:dev
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 5000:5000
