/**
 * Harpocrates API
 * This is the Rest API specification for the Harpocrates application
 *
 * The version of the OpenAPI document: 8.2.0-textContentClassifications.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@HarpocratesApiClient);
  }
}(this, function(expect, @HarpocratesApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @HarpocratesApiClient.PredictedClassification();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PredictedClassification', function() {
    it('should create an instance of PredictedClassification', function() {
      // uncomment below and update the code to test PredictedClassification
      //var instane = new @HarpocratesApiClient.PredictedClassification();
      //expect(instance).to.be.a(@HarpocratesApiClient.PredictedClassification);
    });

    it('should have the property sensitive (base name: "sensitive")', function() {
      // uncomment below and update the code to test the property sensitive
      //var instane = new @HarpocratesApiClient.PredictedClassification();
      //expect(instance).to.be();
    });

    it('should have the property sensitivity (base name: "sensitivity")', function() {
      // uncomment below and update the code to test the property sensitivity
      //var instane = new @HarpocratesApiClient.PredictedClassification();
      //expect(instance).to.be();
    });

    it('should have the property classifier (base name: "classifier")', function() {
      // uncomment below and update the code to test the property classifier
      //var instane = new @HarpocratesApiClient.PredictedClassification();
      //expect(instance).to.be();
    });

    it('should have the property explanations (base name: "explanations")', function() {
      // uncomment below and update the code to test the property explanations
      //var instane = new @HarpocratesApiClient.PredictedClassification();
      //expect(instance).to.be();
    });

  });

}));
