/**
 * Harpocrates API
 * This is the Rest API specification for the Harpocrates application
 *
 * The version of the OpenAPI document: 9.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.api);
  }
}(this, function(expect, api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new api.SensitiveSection();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SensitiveSection', function() {
    it('should create an instance of SensitiveSection', function() {
      // uncomment below and update the code to test SensitiveSection
      //var instane = new api.SensitiveSection();
      //expect(instance).to.be.a(api.SensitiveSection);
    });

    it('should have the property startOffset (base name: "startOffset")', function() {
      // uncomment below and update the code to test the property startOffset
      //var instane = new api.SensitiveSection();
      //expect(instance).to.be();
    });

    it('should have the property endOffset (base name: "endOffset")', function() {
      // uncomment below and update the code to test the property endOffset
      //var instane = new api.SensitiveSection();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instane = new api.SensitiveSection();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new api.SensitiveSection();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new api.SensitiveSection();
      //expect(instance).to.be();
    });

  });

}));
