/**
 * Harpocrates API
 * This is the Rest API specification for the harpocrates application
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PredictedClassificationExplanationFeatures model module.
 * @module model/PredictedClassificationExplanationFeatures
 * @version 0.2.2
 */
class PredictedClassificationExplanationFeatures {
    /**
     * Constructs a new <code>PredictedClassificationExplanationFeatures</code>.
     * an object representing a feature that explains the classification
     * @alias module:model/PredictedClassificationExplanationFeatures
     */
    constructor() { 
        
        PredictedClassificationExplanationFeatures.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PredictedClassificationExplanationFeatures</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PredictedClassificationExplanationFeatures} obj Optional instance to populate.
     * @return {module:model/PredictedClassificationExplanationFeatures} The populated <code>PredictedClassificationExplanationFeatures</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PredictedClassificationExplanationFeatures();

            if (data.hasOwnProperty('feature')) {
                obj['feature'] = ApiClient.convertToType(data['feature'], 'String');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * A feature of the text
 * @member {String} feature
 */
PredictedClassificationExplanationFeatures.prototype['feature'] = undefined;

/**
 * The contribution of that feature to the classification
 * @member {Number} weight
 */
PredictedClassificationExplanationFeatures.prototype['weight'] = undefined;






export default PredictedClassificationExplanationFeatures;

