/**
 * Harpocrates API
 * This is the Rest API specification for the Harpocrates application
 *
 * The version of the OpenAPI document: 9.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FeatureAllOf model module.
 * @module model/FeatureAllOf
 * @version 9.0.0
 */
class FeatureAllOf {
    /**
     * Constructs a new <code>FeatureAllOf</code>.
     * an object representing a feature that explains the classification
     * @alias module:model/FeatureAllOf
     */
    constructor() { 
        
        FeatureAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FeatureAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FeatureAllOf} obj Optional instance to populate.
     * @return {module:model/FeatureAllOf} The populated <code>FeatureAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeatureAllOf();

            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The contribution of that feature to the classification, if positive weight, this feature contributes to a document's sensitivity and conversely
 * @member {Number} weight
 */
FeatureAllOf.prototype['weight'] = undefined;






export default FeatureAllOf;

