/**
 * Harpocrates API
 * This is the Rest API specification for the Harpocrates application
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Feature from './Feature';

/**
 * The PredictedClassification model module.
 * @module model/PredictedClassification
 * @version 5.0.0
 */
class PredictedClassification {
    /**
     * Constructs a new <code>PredictedClassification</code>.
     * The predicted Sensitivity (Sensitive or Not) of a document along with feature explanation for that classification
     * @alias module:model/PredictedClassification
     * @param sensitive {Boolean} true if the document is predicted to be sensitive, false otherwise
     */
    constructor(sensitive) { 
        
        PredictedClassification.initialize(this, sensitive);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sensitive) { 
        obj['sensitive'] = sensitive;
    }

    /**
     * Constructs a <code>PredictedClassification</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PredictedClassification} obj Optional instance to populate.
     * @return {module:model/PredictedClassification} The populated <code>PredictedClassification</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PredictedClassification();

            if (data.hasOwnProperty('sensitive')) {
                obj['sensitive'] = ApiClient.convertToType(data['sensitive'], 'Boolean');
            }
            if (data.hasOwnProperty('sensitivity')) {
                obj['sensitivity'] = ApiClient.convertToType(data['sensitivity'], 'Number');
            }
            if (data.hasOwnProperty('sensitiveFeatures')) {
                obj['sensitiveFeatures'] = ApiClient.convertToType(data['sensitiveFeatures'], [Feature]);
            }
            if (data.hasOwnProperty('nonSensitiveFeatures')) {
                obj['nonSensitiveFeatures'] = ApiClient.convertToType(data['nonSensitiveFeatures'], [Feature]);
            }
        }
        return obj;
    }


}

/**
 * true if the document is predicted to be sensitive, false otherwise
 * @member {Boolean} sensitive
 */
PredictedClassification.prototype['sensitive'] = undefined;

/**
 * Document sensitivity percentage
 * @member {Number} sensitivity
 */
PredictedClassification.prototype['sensitivity'] = undefined;

/**
 * The explanation for the \"sensitive\" classification of a document as an array of features and their contribution to the explanation
 * @member {Array.<module:model/Feature>} sensitiveFeatures
 */
PredictedClassification.prototype['sensitiveFeatures'] = undefined;

/**
 * The explanation for the \"non sensitive\" classification of a document as an array of features and their contribution to the explanation
 * @member {Array.<module:model/Feature>} nonSensitiveFeatures
 */
PredictedClassification.prototype['nonSensitiveFeatures'] = undefined;






export default PredictedClassification;

