/**
 * Harpocrates API
 * This is the Rest API specification for the Harpocrates application
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Feature from './Feature';

/**
 * The PredictedClassificationWithExplanationAllOf model module.
 * @module model/PredictedClassificationWithExplanationAllOf
 * @version 3.0.0
 */
class PredictedClassificationWithExplanationAllOf {
    /**
     * Constructs a new <code>PredictedClassificationWithExplanationAllOf</code>.
     * Object representing an explanation for a sensitivity prediction
     * @alias module:model/PredictedClassificationWithExplanationAllOf
     */
    constructor() { 
        
        PredictedClassificationWithExplanationAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PredictedClassificationWithExplanationAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PredictedClassificationWithExplanationAllOf} obj Optional instance to populate.
     * @return {module:model/PredictedClassificationWithExplanationAllOf} The populated <code>PredictedClassificationWithExplanationAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PredictedClassificationWithExplanationAllOf();

            if (data.hasOwnProperty('sensitiveFeatures')) {
                obj['sensitiveFeatures'] = ApiClient.convertToType(data['sensitiveFeatures'], [Feature]);
            }
            if (data.hasOwnProperty('nonSensitiveFeatures')) {
                obj['nonSensitiveFeatures'] = ApiClient.convertToType(data['nonSensitiveFeatures'], [Feature]);
            }
        }
        return obj;
    }


}

/**
 * The explanation for the \"sensitive\" classification of a document as an array of features and their contribution to the explanation
 * @member {Array.<module:model/Feature>} sensitiveFeatures
 */
PredictedClassificationWithExplanationAllOf.prototype['sensitiveFeatures'] = undefined;

/**
 * The explanation for the \"non sensitive\" classification of a document as an array of features and their contribution to the explanation
 * @member {Array.<module:model/Feature>} nonSensitiveFeatures
 */
PredictedClassificationWithExplanationAllOf.prototype['nonSensitiveFeatures'] = undefined;






export default PredictedClassificationWithExplanationAllOf;

