/**
 * Harpocrates API
 * This is the Rest API specification for the Harpocrates application
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Section from './Section';
import SensitiveSectionAllOf from './SensitiveSectionAllOf';

/**
 * The SensitiveSection model module.
 * @module model/SensitiveSection
 * @version 3.0.0
 */
class SensitiveSection {
    /**
     * Constructs a new <code>SensitiveSection</code>.
     * @alias module:model/SensitiveSection
     * @implements module:model/Section
     * @implements module:model/SensitiveSectionAllOf
     * @param startOffset {Number} start offset of a section in characters from the beginning of the document
     * @param endOffset {Number} end offset of a section in characters from the beginning of the document
     */
    constructor(startOffset, endOffset) { 
        Section.initialize(this, startOffset, endOffset);SensitiveSectionAllOf.initialize(this);
        SensitiveSection.initialize(this, startOffset, endOffset);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startOffset, endOffset) { 
        obj['startOffset'] = startOffset;
        obj['endOffset'] = endOffset;
    }

    /**
     * Constructs a <code>SensitiveSection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SensitiveSection} obj Optional instance to populate.
     * @return {module:model/SensitiveSection} The populated <code>SensitiveSection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SensitiveSection();
            Section.constructFromObject(data, obj);
            SensitiveSectionAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('startOffset')) {
                obj['startOffset'] = ApiClient.convertToType(data['startOffset'], 'Number');
            }
            if (data.hasOwnProperty('endOffset')) {
                obj['endOffset'] = ApiClient.convertToType(data['endOffset'], 'Number');
            }
            if (data.hasOwnProperty('fullAnnotation')) {
                obj['fullAnnotation'] = ApiClient.convertToType(data['fullAnnotation'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * start offset of a section in characters from the beginning of the document
 * @member {Number} startOffset
 */
SensitiveSection.prototype['startOffset'] = undefined;

/**
 * end offset of a section in characters from the beginning of the document
 * @member {Number} endOffset
 */
SensitiveSection.prototype['endOffset'] = undefined;

/**
 * For debugging purposes, the full text of the annotation
 * @member {String} fullAnnotation
 */
SensitiveSection.prototype['fullAnnotation'] = undefined;

/**
 * what was the exemption that was found (mandatory)
 * @member {String} name
 */
SensitiveSection.prototype['name'] = undefined;

/**
 * This is an optional textual description of what the predicted sensitivity is, suitable for presentation to the user
 * @member {String} description
 */
SensitiveSection.prototype['description'] = undefined;


// Implement Section interface:
/**
 * start offset of a section in characters from the beginning of the document
 * @member {Number} startOffset
 */
Section.prototype['startOffset'] = undefined;
/**
 * end offset of a section in characters from the beginning of the document
 * @member {Number} endOffset
 */
Section.prototype['endOffset'] = undefined;
// Implement SensitiveSectionAllOf interface:
/**
 * For debugging purposes, the full text of the annotation
 * @member {String} fullAnnotation
 */
SensitiveSectionAllOf.prototype['fullAnnotation'] = undefined;
/**
 * what was the exemption that was found (mandatory)
 * @member {String} name
 */
SensitiveSectionAllOf.prototype['name'] = undefined;
/**
 * This is an optional textual description of what the predicted sensitivity is, suitable for presentation to the user
 * @member {String} description
 */
SensitiveSectionAllOf.prototype['description'] = undefined;




export default SensitiveSection;

