/**
 * Harpocrates API
 * This is the Rest API specification for the Harpocrates application
 *
 * The version of the OpenAPI document: 9.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PredictedClassification from './PredictedClassification';
import SensitiveSections from './SensitiveSections';

/**
 * The TextContent model module.
 * @module model/TextContent
 * @version 9.2.1
 */
class TextContent {
    /**
     * Constructs a new <code>TextContent</code>.
     * A textContent from a document
     * @alias module:model/TextContent
     * @param content {String} content of the textContent
     */
    constructor(content) { 
        
        TextContent.initialize(this, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content) { 
        obj['content'] = content;
    }

    /**
     * Constructs a <code>TextContent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TextContent} obj Optional instance to populate.
     * @return {module:model/TextContent} The populated <code>TextContent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TextContent();

            if (data.hasOwnProperty('predictedClassification')) {
                obj['predictedClassification'] = PredictedClassification.constructFromObject(data['predictedClassification']);
            }
            if (data.hasOwnProperty('sensitiveSections')) {
                obj['sensitiveSections'] = SensitiveSections.constructFromObject(data['sensitiveSections']);
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PredictedClassification} predictedClassification
 */
TextContent.prototype['predictedClassification'] = undefined;

/**
 * @member {module:model/SensitiveSections} sensitiveSections
 */
TextContent.prototype['sensitiveSections'] = undefined;

/**
 * content of the textContent
 * @member {String} content
 */
TextContent.prototype['content'] = undefined;






export default TextContent;

