# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from harpocrates_server.models.base_model import Model
from harpocrates_server import util


class HttpStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, message=None):  # noqa: E501
        """HttpStatus - a model defined in OpenAPI

        :param code: The code of this HttpStatus.  # noqa: E501
        :type code: int
        :param message: The message of this HttpStatus.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'code': int,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }

        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'HttpStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The httpStatus of this HttpStatus.  # noqa: E501
        :rtype: HttpStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this HttpStatus.

        HTTP status code  # noqa: E501

        :return: The code of this HttpStatus.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this HttpStatus.

        HTTP status code  # noqa: E501

        :param code: The code of this HttpStatus.
        :type code: int
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501
        if code is not None and code > 600:  # noqa: E501
            raise ValueError("Invalid value for `code`, must be a value less than or equal to `600`")  # noqa: E501
        if code is not None and code < 100:  # noqa: E501
            raise ValueError("Invalid value for `code`, must be a value greater than or equal to `100`")  # noqa: E501

        self._code = code

    @property
    def message(self):
        """Gets the message of this HttpStatus.

        HTTP status message  # noqa: E501

        :return: The message of this HttpStatus.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this HttpStatus.

        HTTP status message  # noqa: E501

        :param message: The message of this HttpStatus.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
