# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from harpocrates_server.models.base_model_ import Model
from harpocrates_server import util


class InlineObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, files=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI

        :param files: The files of this InlineObject.  # noqa: E501
        :type files: List[file]
        """
        self.openapi_types = {
            'files': List[file]
        }

        self.attribute_map = {
            'files': 'files'
        }

        self._files = files

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object of this InlineObject.  # noqa: E501
        :rtype: InlineObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def files(self):
        """Gets the files of this InlineObject.


        :return: The files of this InlineObject.
        :rtype: List[file]
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this InlineObject.


        :param files: The files of this InlineObject.
        :type files: List[file]
        """

        self._files = files
