version: 1
update_configs:
  - package_manager: "javascript"
    target_branch: master
    directory: "/frontend"
    update_schedule: "live"

  - package_manager: "javascript"
    target_branch: master
    directory: "/js-api-client"
    update_schedule: "live"

  - package_manager: "python"
    target_branch: master
    directory: "/api"
    update_schedule: "live"

  - package_manager: "docker"
    target_branch: master
    directory: "/frontend"
    update_schedule: "daily"

  - package_manager: "docker"
    target_branch: master
    directory: "/api"
    update_schedule: "daily"
