# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.predicted_classification_with_explanation import PredictedClassificationWithExplanation
from openapi_server import util

from openapi_server.models.predicted_classification_with_explanation import PredictedClassificationWithExplanation  # noqa: E501

class Document(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, document_id=None, predicted_classification_with_explanation=None, content=None):  # noqa: E501
        """Document - a model defined in OpenAPI

        :param name: The name of this Document.  # noqa: E501
        :type name: str
        :param document_id: The document_id of this Document.  # noqa: E501
        :type document_id: str
        :param predicted_classification_with_explanation: The predicted_classification_with_explanation of this Document.  # noqa: E501
        :type predicted_classification_with_explanation: PredictedClassificationWithExplanation
        :param content: The content of this Document.  # noqa: E501
        :type content: str
        """
        self.openapi_types = {
            'name': str,
            'document_id': str,
            'predicted_classification_with_explanation': PredictedClassificationWithExplanation,
            'content': str
        }

        self.attribute_map = {
            'name': 'name',
            'document_id': 'documentId',
            'predicted_classification_with_explanation': 'predictedClassificationWithExplanation',
            'content': 'content'
        }

        self._name = name
        self._document_id = document_id
        self._predicted_classification_with_explanation = predicted_classification_with_explanation
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'Document':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The document of this Document.  # noqa: E501
        :rtype: Document
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this Document.


        :return: The name of this Document.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Document.


        :param name: The name of this Document.
        :type name: str
        """

        self._name = name

    @property
    def document_id(self):
        """Gets the document_id of this Document.


        :return: The document_id of this Document.
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id):
        """Sets the document_id of this Document.


        :param document_id: The document_id of this Document.
        :type document_id: str
        """
        if document_id is None:
            raise ValueError("Invalid value for `document_id`, must not be `None`")  # noqa: E501

        self._document_id = document_id

    @property
    def predicted_classification_with_explanation(self):
        """Gets the predicted_classification_with_explanation of this Document.


        :return: The predicted_classification_with_explanation of this Document.
        :rtype: PredictedClassificationWithExplanation
        """
        return self._predicted_classification_with_explanation

    @predicted_classification_with_explanation.setter
    def predicted_classification_with_explanation(self, predicted_classification_with_explanation):
        """Sets the predicted_classification_with_explanation of this Document.


        :param predicted_classification_with_explanation: The predicted_classification_with_explanation of this Document.
        :type predicted_classification_with_explanation: PredictedClassificationWithExplanation
        """

        self._predicted_classification_with_explanation = predicted_classification_with_explanation

    @property
    def content(self):
        """Gets the content of this Document.

        content of the document  # noqa: E501

        :return: The content of this Document.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this Document.

        content of the document  # noqa: E501

        :param content: The content of this Document.
        :type content: str
        """

        self._content = content
