# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class FeatureAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, weight=None):  # noqa: E501
        """FeatureAllOf - a model defined in OpenAPI

        :param weight: The weight of this FeatureAllOf.  # noqa: E501
        :type weight: float
        """
        self.openapi_types = {
            'weight': float
        }

        self.attribute_map = {
            'weight': 'weight'
        }

        self._weight = weight

    @classmethod
    def from_dict(cls, dikt) -> 'FeatureAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The feature_allOf of this FeatureAllOf.  # noqa: E501
        :rtype: FeatureAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def weight(self):
        """Gets the weight of this FeatureAllOf.

        The contribution of that feature to the classification  # noqa: E501

        :return: The weight of this FeatureAllOf.
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """Sets the weight of this FeatureAllOf.

        The contribution of that feature to the classification  # noqa: E501

        :param weight: The weight of this FeatureAllOf.
        :type weight: float
        """

        self._weight = weight
