# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.feature import Feature
from openapi_server import util

from openapi_server.models.feature import Feature  # noqa: E501

class PredictedClassificationWithExplanationAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sensitive_features=None, non_sensitive_features=None):  # noqa: E501
        """PredictedClassificationWithExplanationAllOf - a model defined in OpenAPI

        :param sensitive_features: The sensitive_features of this PredictedClassificationWithExplanationAllOf.  # noqa: E501
        :type sensitive_features: List[Feature]
        :param non_sensitive_features: The non_sensitive_features of this PredictedClassificationWithExplanationAllOf.  # noqa: E501
        :type non_sensitive_features: List[Feature]
        """
        self.openapi_types = {
            'sensitive_features': List[Feature],
            'non_sensitive_features': List[Feature]
        }

        self.attribute_map = {
            'sensitive_features': 'sensitiveFeatures',
            'non_sensitive_features': 'nonSensitiveFeatures'
        }

        self._sensitive_features = sensitive_features
        self._non_sensitive_features = non_sensitive_features

    @classmethod
    def from_dict(cls, dikt) -> 'PredictedClassificationWithExplanationAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The predictedClassificationWithExplanation_allOf of this PredictedClassificationWithExplanationAllOf.  # noqa: E501
        :rtype: PredictedClassificationWithExplanationAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sensitive_features(self):
        """Gets the sensitive_features of this PredictedClassificationWithExplanationAllOf.

        The explanation for the \"sensitive\" classification of a document as an array of features and their contribution to the explanation  # noqa: E501

        :return: The sensitive_features of this PredictedClassificationWithExplanationAllOf.
        :rtype: List[Feature]
        """
        return self._sensitive_features

    @sensitive_features.setter
    def sensitive_features(self, sensitive_features):
        """Sets the sensitive_features of this PredictedClassificationWithExplanationAllOf.

        The explanation for the \"sensitive\" classification of a document as an array of features and their contribution to the explanation  # noqa: E501

        :param sensitive_features: The sensitive_features of this PredictedClassificationWithExplanationAllOf.
        :type sensitive_features: List[Feature]
        """

        self._sensitive_features = sensitive_features

    @property
    def non_sensitive_features(self):
        """Gets the non_sensitive_features of this PredictedClassificationWithExplanationAllOf.

        The explanation for the \"non sensitive\" classification of a document as an array of features and their contribution to the explanation  # noqa: E501

        :return: The non_sensitive_features of this PredictedClassificationWithExplanationAllOf.
        :rtype: List[Feature]
        """
        return self._non_sensitive_features

    @non_sensitive_features.setter
    def non_sensitive_features(self, non_sensitive_features):
        """Sets the non_sensitive_features of this PredictedClassificationWithExplanationAllOf.

        The explanation for the \"non sensitive\" classification of a document as an array of features and their contribution to the explanation  # noqa: E501

        :param non_sensitive_features: The non_sensitive_features of this PredictedClassificationWithExplanationAllOf.
        :type non_sensitive_features: List[Feature]
        """

        self._non_sensitive_features = non_sensitive_features
