# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class SensitiveSectionAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, full_annotation=None, name=None, description=None):  # noqa: E501
        """SensitiveSectionAllOf - a model defined in OpenAPI

        :param full_annotation: The full_annotation of this SensitiveSectionAllOf.  # noqa: E501
        :type full_annotation: str
        :param name: The name of this SensitiveSectionAllOf.  # noqa: E501
        :type name: str
        :param description: The description of this SensitiveSectionAllOf.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'full_annotation': str,
            'name': str,
            'description': str
        }

        self.attribute_map = {
            'full_annotation': 'fullAnnotation',
            'name': 'name',
            'description': 'description'
        }

        self._full_annotation = full_annotation
        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'SensitiveSectionAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The sensitiveSection_allOf of this SensitiveSectionAllOf.  # noqa: E501
        :rtype: SensitiveSectionAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def full_annotation(self):
        """Gets the full_annotation of this SensitiveSectionAllOf.

        For debugging purposes, the full text of the annotation  # noqa: E501

        :return: The full_annotation of this SensitiveSectionAllOf.
        :rtype: str
        """
        return self._full_annotation

    @full_annotation.setter
    def full_annotation(self, full_annotation):
        """Sets the full_annotation of this SensitiveSectionAllOf.

        For debugging purposes, the full text of the annotation  # noqa: E501

        :param full_annotation: The full_annotation of this SensitiveSectionAllOf.
        :type full_annotation: str
        """

        self._full_annotation = full_annotation

    @property
    def name(self):
        """Gets the name of this SensitiveSectionAllOf.

        what was the exemption that was found (mandatory)  # noqa: E501

        :return: The name of this SensitiveSectionAllOf.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SensitiveSectionAllOf.

        what was the exemption that was found (mandatory)  # noqa: E501

        :param name: The name of this SensitiveSectionAllOf.
        :type name: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this SensitiveSectionAllOf.

        This is an optional textual description of what the predicted sensitivity is, suitable for presentation to the user  # noqa: E501

        :return: The description of this SensitiveSectionAllOf.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SensitiveSectionAllOf.

        This is an optional textual description of what the predicted sensitivity is, suitable for presentation to the user  # noqa: E501

        :param description: The description of this SensitiveSectionAllOf.
        :type description: str
        """

        self._description = description
