# coding: utf-8

from __future__ import absolute_import

from openapi_server import util
from openapi_server.models.base_model_ import Model


class Document(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, id=None, content=None):  # noqa: E501
        """Document - a model defined in OpenAPI

        :param name: The name of this Document.  # noqa: E501
        :type name: str
        :param id: The id of this Document.  # noqa: E501
        :type id: int
        :param content: The content of this Document.  # noqa: E501
        :type content: str
        """
        self.openapi_types = {
            'name': str,
            'id': int,
            'content': str
        }

        self.attribute_map = {
            'name': 'name',
            'id': 'id',
            'content': 'content'
        }

        self._name = name
        self._id = id
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'Document':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The document of this Document.  # noqa: E501
        :rtype: Document
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this Document.


        :return: The name of this Document.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Document.


        :param name: The name of this Document.
        :type name: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this Document.


        :return: The id of this Document.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Document.


        :param id: The id of this Document.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def content(self):
        """Gets the content of this Document.


        :return: The content of this Document.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this Document.


        :param content: The content of this Document.
        :type content: str
        """

        self._content = content
