# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Feature(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, feature=None, weight=None):  # noqa: E501
        """Feature - a model defined in OpenAPI

        :param feature: The feature of this Feature.  # noqa: E501
        :type feature: str
        :param weight: The weight of this Feature.  # noqa: E501
        :type weight: float
        """
        self.openapi_types = {
            'feature': str,
            'weight': float
        }

        self.attribute_map = {
            'feature': 'feature',
            'weight': 'weight'
        }

        self._feature = feature
        self._weight = weight

    @classmethod
    def from_dict(cls, dikt) -> 'Feature':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The feature of this Feature.  # noqa: E501
        :rtype: Feature
        """
        return util.deserialize_model(dikt, cls)

    @property
    def feature(self):
        """Gets the feature of this Feature.

        A feature of the text  # noqa: E501

        :return: The feature of this Feature.
        :rtype: str
        """
        return self._feature

    @feature.setter
    def feature(self, feature):
        """Sets the feature of this Feature.

        A feature of the text  # noqa: E501

        :param feature: The feature of this Feature.
        :type feature: str
        """
        if feature is None:
            raise ValueError("Invalid value for `feature`, must not be `None`")  # noqa: E501

        self._feature = feature

    @property
    def weight(self):
        """Gets the weight of this Feature.

        The contribution of that feature to the classification  # noqa: E501

        :return: The weight of this Feature.
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """Sets the weight of this Feature.

        The contribution of that feature to the classification  # noqa: E501

        :param weight: The weight of this Feature.
        :type weight: float
        """

        self._weight = weight
