# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, explanations=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI

        :param explanations: The explanations of this InlineResponse200.  # noqa: E501
        :type explanations: List
        """
        self.openapi_types = {
            'explanations': List
        }

        self.attribute_map = {
            'explanations': 'explanations'
        }

        self._explanations = explanations

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def explanations(self):
        """Gets the explanations of this InlineResponse200.


        :return: The explanations of this InlineResponse200.
        :rtype: List
        """
        return self._explanations

    @explanations.setter
    def explanations(self, explanations):
        """Sets the explanations of this InlineResponse200.


        :param explanations: The explanations of this InlineResponse200.
        :type explanations: List
        """

        self._explanations = explanations
