# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.predicted_classification_explanation_features import PredictedClassificationExplanationFeatures
from openapi_server import util

from openapi_server.models.predicted_classification_explanation_features import PredictedClassificationExplanationFeatures  # noqa: E501

class PredictedClassificationExplanation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, features=None):  # noqa: E501
        """PredictedClassificationExplanation - a model defined in OpenAPI

        :param features: The features of this PredictedClassificationExplanation.  # noqa: E501
        :type features: List[PredictedClassificationExplanationFeatures]
        """
        self.openapi_types = {
            'features': List[PredictedClassificationExplanationFeatures]
        }

        self.attribute_map = {
            'features': 'features'
        }

        self._features = features

    @classmethod
    def from_dict(cls, dikt) -> 'PredictedClassificationExplanation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The predictedClassificationExplanation of this PredictedClassificationExplanation.  # noqa: E501
        :rtype: PredictedClassificationExplanation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def features(self):
        """Gets the features of this PredictedClassificationExplanation.

        The explanation for the predicted sensitivity classification of a document as an array of features and their contribution to the explanation  # noqa: E501

        :return: The features of this PredictedClassificationExplanation.
        :rtype: List[PredictedClassificationExplanationFeatures]
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this PredictedClassificationExplanation.

        The explanation for the predicted sensitivity classification of a document as an array of features and their contribution to the explanation  # noqa: E501

        :param features: The features of this PredictedClassificationExplanation.
        :type features: List[PredictedClassificationExplanationFeatures]
        """

        self._features = features
